//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class CandidatePilot : Person
    {
        public CandidatePilot()
        {
            this.ExamPilots = new HashSet<ExamPilot>();
        }
    
    	public string ARN { get; set; }
    	public bool InstrumentRating { get; set; }
    	public bool ValidBFR { get; set; }
    	public System.DateTime PilotMedicalExpiryDate { get; set; }
    	public System.Guid CreatedBy { get; set; }
    	public System.Guid AddressId { get; set; }
    	public string Email { get; set; }
    	public string PhoneNumber { get; set; }
    	public string MobileNumber { get; set; }
    	public System.DateTime DateOfBirth { get; set; }
    	public Nullable<short> PilotLicenseType { get; set; }
    	public Nullable<short> PilotMedicalType { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Examiner Examiner { get; set; }
        public virtual ICollection<ExamPilot> ExamPilots { get; set; }
    }
}
