//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailDataContract", Namespace="http://schemas.datacontract.org/2004/07/EmailService")]
    public partial class EmailDataContract : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BodyField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] ExamField;
        
        private int ExamTypeField;
        
        private string SubjectField;
        
        private string ToAddressField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] Exam
        {
            get
            {
                return this.ExamField;
            }
            set
            {
                this.ExamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamType
        {
            get
            {
                return this.ExamTypeField;
            }
            set
            {
                this.ExamTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddress
        {
            get
            {
                return this.ToAddressField;
            }
            set
            {
                this.ToAddressField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEmailServiceOperation")]
public interface IEmailServiceOperation
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailServiceOperation/SendEmail", ReplyAction="http://tempuri.org/IEmailServiceOperation/SendEmailResponse")]
    void SendEmail(EmailService.EmailDataContract emailData);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailServiceOperation/SendEmail", ReplyAction="http://tempuri.org/IEmailServiceOperation/SendEmailResponse")]
    System.Threading.Tasks.Task SendEmailAsync(EmailService.EmailDataContract emailData);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEmailServiceOperationChannel : IEmailServiceOperation, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EmailServiceOperationClient : System.ServiceModel.ClientBase<IEmailServiceOperation>, IEmailServiceOperation
{
    
    public EmailServiceOperationClient()
    {
    }
    
    public EmailServiceOperationClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EmailServiceOperationClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmailServiceOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmailServiceOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SendEmail(EmailService.EmailDataContract emailData)
    {
        base.Channel.SendEmail(emailData);
    }
    
    public System.Threading.Tasks.Task SendEmailAsync(EmailService.EmailDataContract emailData)
    {
        return base.Channel.SendEmailAsync(emailData);
    }
}
