//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class ExaminerAuthority
    {
    	public System.Guid Id { get; set; }
    	public System.Guid ExaminerId { get; set; }
    	public int ExamTypeId { get; set; }
    	public APFTestingModel.ExamTypeEnum ExamType { get; set; }
    
        public virtual Examiner Examiner { get; set; }
    }
}
