//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Examiner : Person
    {
        public Examiner()
        {
            this.CandidatePackers = new HashSet<CandidatePacker>();
            this.CandidatePilots = new HashSet<CandidatePilot>();
            this.Exams = new HashSet<Exam>();
            this.ExaminerAuthorities = new HashSet<ExaminerAuthority>();
        }
    
    	public int UserId { get; set; }
    	public string APFNumber { get; set; }
    	public bool IsActive { get; set; }
    
        public virtual ICollection<CandidatePacker> CandidatePackers { get; set; }
        public virtual ICollection<CandidatePilot> CandidatePilots { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<ExaminerAuthority> ExaminerAuthorities { get; set; }
        public virtual User User { get; set; }
    }
}
