//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examiner
    {
        public Examiner()
        {
            this.TheoryComponents = new HashSet<TheoryComponent>();
        }
    
        public System.Guid id { get; set; }
    
        public virtual ICollection<TheoryComponent> TheoryComponents { get; set; }
    }
}
