//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APFTestingDBEntities : DbContext
    {
        public APFTestingDBEntities()
            : base("name=APFTestingDBEntities")
        {
    			AssessmentTaskPackers = Set<AssessmentTaskPacker>();	
    		AssessmentTaskPilots = Set<AssessmentTaskPilot>();	
    		Exams = Set<Exam>();	
    		PossibleAnswers = Set<PossibleAnswer>();	
    		PracticalComponents = Set<PracticalComponent>();	
    		PracticalComponentTemplates = Set<PracticalComponentTemplate>();	
    		SelectedAssessmentTasks = Set<SelectedAssessmentTask>();	
    		SelectedTheoryQuestions = Set<SelectedTheoryQuestion>();	
    		TheoryComponents = Set<TheoryComponent>();	
    		TheoryComponentFormats = Set<TheoryComponentFormat>();	
    		TheoryQuestions = Set<TheoryQuestion>();	
    
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AssessmentTaskPacker> AssessmentTaskPackers { get; set; }
        public DbSet<AssessmentTaskPilot> AssessmentTaskPilots { get; set; }
        public DbSet<Exam> Exams { get; set; }
        public DbSet<PossibleAnswer> PossibleAnswers { get; set; }
        public DbSet<PracticalComponent> PracticalComponents { get; set; }
        public DbSet<PracticalComponentTemplate> PracticalComponentTemplates { get; set; }
        public DbSet<SelectedAssessmentTask> SelectedAssessmentTasks { get; set; }
        public DbSet<SelectedTheoryQuestion> SelectedTheoryQuestions { get; set; }
        public DbSet<TheoryComponent> TheoryComponents { get; set; }
        public DbSet<TheoryComponentFormat> TheoryComponentFormats { get; set; }
        public DbSet<TheoryQuestion> TheoryQuestions { get; set; }
    }
}
