//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class PossibleAnswer
    {
        public PossibleAnswer()
        {
            this.SelectedAnswers = new HashSet<SelectedAnswer>();
            this.TheoryQuestions = new HashSet<TheoryQuestion>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public bool IsCorrect { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<SelectedAnswer> SelectedAnswers { get; set; }
        public virtual ICollection<TheoryQuestion> TheoryQuestions { get; set; }
    }
}
