
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace APFTestingModel
{

using System;
    using System.Collections.Generic;
    
internal partial class PossibleAnswer
{

	public System.Guid Id { get; set; }

	public System.Guid SelectedTheoryQuestionId { get; set; }

	public System.Guid AnswerId { get; set; }

	public System.DateTime SelectedTime { get; set; }

	public bool IsChecked { get; set; }



    public virtual Answer Answer { get; set; }

    public virtual SelectedTheoryQuestion SelectedTheoryQuestion { get; set; }

}

}
