//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class PracticalComponentItemResult
    {
        public System.Guid PracticalComponentId { get; set; }
        public System.Guid PracticalQuestionId { get; set; }
        public string Comment { get; set; }
        public int Score { get; set; }
    
        public virtual PracticalComponent PracticalComponent { get; set; }
        public virtual PracticalComponentItem PracticalComponentItem { get; set; }
    }
}
