//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticalComponent
    {
        public PracticalComponent()
        {
            this.Exams = new HashSet<Exam>();
            this.PracticalComponentItemResults = new HashSet<PracticalComponentItemResult>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ExaminerId { get; set; }
        public System.Guid PracticalTemplateId { get; set; }
    
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual PracticalComponentTemplate PracticalComponentTemplate { get; set; }
        public virtual ICollection<PracticalComponentItemResult> PracticalComponentItemResults { get; set; }
    }
}
