
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace APFTestingModel
{

using System;
    using System.Collections.Generic;
    
internal partial class PracticalComponentPilot : PracticalComponent
{

    public PracticalComponentPilot()
    {

        this.SelectedAssessmentTasks = new HashSet<SelectedAssessmentTask>();

        this.ExamPilots = new HashSet<ExamPilot>();

    }


	public System.Guid TemplateId { get; set; }



    public virtual ICollection<SelectedAssessmentTask> SelectedAssessmentTasks { get; set; }

    public virtual ICollection<ExamPilot> ExamPilots { get; set; }

    public virtual PracticalComponentTemplatePilot PracticalComponentTemplatePilot { get; set; }

}

}
