//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class PracticalComponentItem
    {
        public PracticalComponentItem()
        {
            this.PracticalComponentItemResults = new HashSet<PracticalComponentItemResult>();
            this.PracticalComponentTemplates = new HashSet<PracticalComponentTemplate>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public int MaxScore { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<PracticalComponentItemResult> PracticalComponentItemResults { get; set; }
        public virtual ICollection<PracticalComponentTemplate> PracticalComponentTemplates { get; set; }
    }
}
