//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal abstract partial class PracticalComponent
    {
        public PracticalComponent()
        {
            this.Exams = new HashSet<Exam>();
        }
    
    	public System.Guid Id { get; set; }
    	public System.DateTime CreationDate { get; set; }
    	public System.Guid TemplateId { get; set; }
    
        public virtual PracticalComponentTemplate PracticalComponentTemplate { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
