//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.SelectedOptions = new HashSet<SelectedOption>();
            this.PossibleAnswers = new HashSet<PossibleAnswer>();
            this.TheoryComponents = new HashSet<TheoryComponent>();
        }
    
        public System.Guid Id { get; set; }
        public int NumberOfCorrectAnswer { get; set; }
        public bool IsActive { get; set; }
        public int ExamTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SelectedOption> SelectedOptions { get; set; }
        public virtual ICollection<PossibleAnswer> PossibleAnswers { get; set; }
        public virtual ICollection<TheoryComponent> TheoryComponents { get; set; }
    }
}
