//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class SelectedAssessmentTask
    {
    	public System.Guid Id { get; set; }
    	public System.Guid PracticalComponentId { get; set; }
    	public System.Guid AssessmentTaskPilotId { get; set; }
    	public string Comment { get; set; }
    	public int Score { get; set; }
    
        public virtual AssessmentTaskPilot AssessmentTaskPilot { get; set; }
        public virtual PracticalComponentPilot PracticalComponentPilot { get; set; }
    }
}
