//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class SelectedOption
    {
        public System.Guid QuestionId { get; set; }
        public System.Guid ExamId { get; set; }
        public System.Guid OptionId { get; set; }
    
        public virtual PossibleAnswer PossibleAnswer { get; set; }
        public virtual Question Question { get; set; }
        public virtual TheoryComponent TheoryComponent { get; set; }
    }
}
