//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APFTestingModel
{
    using System;
    using System.Collections.Generic;
    
    internal abstract partial class TheoryComponentFormat
    {
        public TheoryComponentFormat()
        {
            this.TheoryComponents = new HashSet<TheoryComponent>();
        }
    
        public System.Guid Id { get; set; }
        public int NumberOfQuestions { get; set; }
        public int PassMark { get; set; }
        public bool IsActive { get; set; }
        public int TimeLimit { get; set; }
    
        public virtual ICollection<TheoryComponent> TheoryComponents { get; set; }
    }
}
